apiVersion: v1
kind: Service
metadata:
  name: svc-pos-tech-api
spec:
  selector:
    app: pos-tech-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000 # Escolha um número de porta disponível entre 30000-32767